name: Build & Publish Rust Dev Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docker/sanity/**'
  pull_request:
    paths:
      - 'docker/sanity/**'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image: ["sanity"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dotenv Action
        uses: falti/dotenv-action@v0.2.8
        id: dotenv
        with:
          path: docker/${{ matrix.image }}/.env

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{steps.dotenv.outputs.version}}
            type=semver,pattern={{major}}.{{minor}},value=${{steps.dotenv.outputs.version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: docker/${{ matrix.image }}/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
